In [3]:
# Write a function so that the columns of the output matrix are powers of the input
# vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.
#------------------------------------------------------------------------------------------------
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
# Theophile Vandermonde.
#-------------------------------------------------------------------------------------------------
class Error(Exception):
    pass
class customValueError(Error):
    pass
class customTypeError(Error):
    pass
            

In [4]:
import pandas as pd
import numpy as np

def Vander_matrix_custom(x,N=None,increasing=False):
    try:
        new_list=[]
        if N == False:
            print(np.array(new_list))
            
        elif N!=None and N<0:
            raise customValueError
            
        elif N!=None and type(N)!=int:
            raise customTypeError
             
        else:
            for i in range(len(x)):
                for j in x:                
                    new_list.append(j**i)
            matrix = np.array([new_list[i:i+len(x)] for i in range(0,len(new_list),len(x))])
            increasing_vander_matrix = matrix.T
            if increasing == False or increasing ==None:
                a =increasing_vander_matrix.tolist()
                reversed_mat = []
                for i in range(len(a)):
                    b = a[i]
                    reversed_mat.append(b[::-1]) 
                print(np.mat(reversed_mat))
            else:
                print(increasing_vander_matrix)
    except customValueError:
        print('Value error! Negative dimensions not allowed!')   
    except customTypeError:
            print('Please enter integer') 

In [6]:
# case1: with only one parameter,the default increasing value is 'False' decreasing order of power displayed
# default matrix will consider the N value as length of input vector
vector =[1,2,3,4,5]
x = np.array(vector)
Vander_matrix_custom(x)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [7]:
# case2: while increasing is True, matrix is in increasing order of power
Vander_matrix_custom(x,increasing = True)

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


In [8]:
#case3: N=-1, N value cant be negative
Vander_matrix_custom(x,N=-1)

Value error! Negative dimensions not allowed!


In [9]:
#case4: if N greater than or less than the length of input vector, default length(length of input vector taken)
Vander_matrix_custom(x,N=7)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [10]:
#case5: N=0, no values returned
Vander_matrix_custom(x,N=1.25)

Please enter integer


In [11]:
#case6: on given 'None' for N and increasing, default length of input vector taken,default descending order of power displayed
Vander_matrix_custom(x,N=None,increasing=None)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [ ]:
# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
# the given sequence is defined as follows:
# The moving average sequence has n-k+1 elements as shown below.
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below
# i 1 2 3 4 5 6 7 8 9 10
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100
# y1 25 = (10+20+30+40)/4
# y2 35 = (20+30+40+50)/4
# y3 45 = (30+40+50+60)/4
# y4 55 = (40+50+60+70)/4
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4
# Thus, the moving average sequence has n-k+1=10-4+1=7 values.
#---------------------------------------------------------------------------------
# Question: Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [12]:
class Error(Exception):
    pass
class customValueError(Error):
    pass
class customTypeError(Error):
    pass

In [13]:
def moving_avg_custom(new,k):
    sequences = []
    moving_avg = []
    n =len(new)
    
    if type(k)== int and k>0:
        
#creating the sequences/subsets as per the window size 
        for i in range(len(new)):             
            while (k<=n) == True:
                sequences.append(new[i:k])
                k = k+1   
                break;  
        moving_avg = []
#getting the moving average of each of the subsets       
        for i in range(len(sequences)):
            average = sum(sequences[i])/len(sequences[i])
            moving_avg.append(round(average,2))    
        print(pd.Series(np.array(moving_avg)))
    else:
        try:
            if (k == 0):
                print(sequences)   
            elif (k<0):
                raise customValueError
                    
            else:
                type(k)!=int
                raise customTypeError
                    
        except customValueError:
            print('Please enter a window size(k) greater than zero!')
        except customTypeError:
            print('Window size must be integer')

In [14]:
# returning an array with the moving averge for the window size = 3
#Case1:
l =[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
new =np.array(l)
k = 3
moving_avg_custom(new,k)

0       5.00
1       4.67
2       5.67
3       6.67
4       9.67
5      28.67
6      49.33
7      72.67
8      84.00
9      93.33
10    116.33
dtype: float64


In [15]:
#Case2: if window size is zero, empty array displayed
moving_avg_custom(new,0)

[]


In [16]:
#Case3: window size should be integer
moving_avg_custom(new,1.25)

Window size must be integer


In [18]:
#Case4: negative window size not accepted
moving_avg_custom(new,-1)

Please enter a window size(k) greater than zero!
